title:            malware busted!
description:      malware found at IT busters spamtraps
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:	  Home
    url:	  /
  - name:         About
    url:          /about
  - name:         IT Busters
    url:          https://itbusters.pl
    external:     true
  - name:         Email
    url:          mailto:team@itbusters.pl
    external:     true
  - name:         GitHub
    url:          https://github.com/itbusters/itbusters.github.io
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
